### PR TITLE
Issue 40151: Show modifications shows HTML code instead of a table of mods

### PR DESCRIPTION
**Pull request by labkey-jeckels**
#### Changes
Avoid double-encoding and use DOM builders

### CODE REVIEW

**Review by labkey-matthewb — APPROVED** [review]
It's a bit more compact if you do import static org.labkey.api.util.DOM.*

Also, I'd encourage you to try to build this all as one statement starting with DOM.TABLE(...) with no ArrayList<> rows.

* you can pass null as a noop, if there is a conditional element (e.g. an optional row)
    ..., cond ? null : TR(TD()), ...
* you can return fragments from a method (list of elements with no wrapping element)
   Renderable appendMods() { ... return DOM.createHtmlFragment(...)}
* These methods can take streams as arguments so.
   createHtmlFragment( mods.entrySet().stream().map(entry -> DOM.TR(...)) )

Approved in case you're not in the mood.

**Comment by labkey-matthewb** [comment]
ModulesView.renderView() is an extreme example

**Comment by labkey-jeckels** [comment]
Thanks Matt, I was hoping you'd have some good tips.  If you don't mind a quick re-review, I think I've updated as suggested.

It's tricky to discover what's a legal argument since most methods take Object... I'll add some JavaDoc that tries to capture these tips.

**Comment by labkey-matthewb** [comment]
I know, I had to pick between varargs... or overloads, can't really do both...

**Review by labkey-matthewb — APPROVED** [review]

**Pull request merged**
